/*
 * $Id: cernlib.h,v 1.6 1998/03/25 10:40:36 hejny Exp $
 * 
 * $Log: cernlib.h,v $
 * Revision 1.6  1998/03/25 10:40:36  hejny
 * Added NORRAN, HBAR2
 *
 * Revision 1.5  1998/03/03 15:42:02  hejny
 * Error calculation for 1D spectra implemented
 *
 * Revision 1.4  1998/03/03 14:55:57  hejny
 * HBARX added
 *
 * Revision 1.3  1998/02/16 16:33:29  hejny
 * Bigfix: V2.4B and earlier are readable again
 *
 * Revision 1.2  1998/01/28 17:26:20  hejny
 * Adding profile histograms to the analysis.
 *
 */

/* ==== cernlib.h is only a short replacement for hbook.h ... =============== */

#if !defined(_CERNLIB_H)
#define _CERNLIB_H

/* ==== hbook =============================================================== */
#define HLIMIT(A1) \
    CCALLSFSUB1(HLIMIT,hlimit,INT,A1)
#define HBOOK1(A1,A2,A3,A4,A5,A6)  \
    CCALLSFSUB6(HBOOK1,hbook1,INT,STRING,INT,FLOAT,FLOAT,FLOAT,A1,A2,A3,A4,A5,A6)
#define HBOOK2(A1,A2,A3,A4,A5,A6,A7,A8,A9)  \
    CCALLSFSUB9(HBOOK2,hbook2,INT,STRING,INT,FLOAT,FLOAT,INT,FLOAT,FLOAT,FLOAT,A1,A2,A3,A4,A5,A6,A7,A8,A9)
#define HBPROF(A1,A2,A3,A4,A5,A6,A7,A8)  \
    CCALLSFSUB8(HBPROF,hbprof,INT,STRING,INT,FLOAT,FLOAT,FLOAT,FLOAT,STRING,A1,A2,A3,A4,A5,A6,A7,A8)
#define HBAR2(A1) \
    CCALLSFSUB1(HBAR2,hbar2,INT,A1)
#define HBARX(A1) \
    CCALLSFSUB1(HBARX,hbarx,INT,A1)
#define HBARY(A1) \
    CCALLSFSUB1(HBARY,hbary,INT,A1)
#define HIDOPT(A1,A2) \
    CCALLSFSUB2(HIDOPT,hidopt,INT,STRING,A1,A2)
#define HFILL(A1,A2,A3,A4)  \
    CCALLSFSUB4(HFILL,hfill,INT,FLOAT,FLOAT,FLOAT,A1,A2,A3,A4)
#define HREBIN(A1,A2,A3,A4,A5,A6,A7,A8)  \
    CCALLSFSUB8(HREBIN,hrebin,INT,PFLOAT,PFLOAT,PFLOAT,PFLOAT,INT,INT,INT,A1,A2,A3,A4,A5,A6,A7,A8)
#define HF1(A1,A2,A4)  \
    CCALLSFSUB3(HF1,hf1,INT,FLOAT,FLOAT,A1,A2,A4)
#define HF2(A1,A2,A3,A4)  \
    CCALLSFSUB4(HF2,hf2,INT,FLOAT,FLOAT,FLOAT,A1,A2,A3,A4)
#define HFF1(A1,A2,A3,A4)  \
    CCALLSFSUB4(HFF1,hff1,INT,PINT,FLOAT,FLOAT,A1,A2,A3,A4)
#define HFF2(A1,A2,A3,A4,A5)  \
    CCALLSFSUB5(HFF2,hff2,INT,PINT,FLOAT,FLOAT,FLOAT,A1,A2,A3,A4,A5)
#define HDELET(A1)  \
    CCALLSFSUB1(HDELET,hdelet,INT,A1)
#define HUNPKE(A1,A2,A3,A4)  \
    CCALLSFSUB4(HUNPKE,hunpke,INT,PFLOAT,STRING,INT,A1,A2,A3,A4)
#define HPAKE(A1,A2)  \
    CCALLSFSUB2(HPAKE,hpake,INT,FLOATV,A1,A2)
#define HUNPAK(A1,A2,A3,A4)  \
    CCALLSFSUB4(HUNPAK,hunpak,INT,PFLOAT,STRING,INT,A1,A2,A3,A4)
#define HPAK(A1,A2)  \
    CCALLSFSUB2(HPAK,hpak,INT,FLOATV,A1,A2)
#define HGIVE(A1,A2,A3,A4,A5,A6,A7,A8,A9,A10)  \
    CCALLSFSUB10(HGIVE,hgive,INT,PSTRING,PINT,PFLOAT,PFLOAT,PINT,PFLOAT,PFLOAT,PINT,PINT,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10)
#define HPLOC(A1,A2,A3,A4,A5,A6,A7,A8) \
    CCALLSFSUB8(HPLOC,hploc,INT,PINT,PFLOAT,PFLOAT,PINT,PINT,PINT,PINT,A1,A2,A3,A4,A5,A6,A7,A8)
#define HPLSIZ(A1,A2,A3) \
    CCALLSFSUB3(HPLSIZ,hplsiz,PFLOAT,PFLOAT,STRING,A1,A2,A3)
#define HPLAX(A1,A2) \
    CCALLSFSUB2(HPLAX,hplax,STRING,STRING,A1,A2)
#define HCDIR(A1,A2) \
    CCALLSFSUB2(HCDIR,hcdir,STRING,STRING,A1,A2)
#define HRGET(A1,A2,A3) \
    CCALLSFSUB3(HRGET,hrget,INT,STRING,STRING,A1,A2,A3)
#define HRPUT(A1,A2,A3) \
    CCALLSFSUB3(HRPUT,hrput,INT,STRING,STRING,A1,A2,A3)
#define HRESET(A1,A2) \
    CCALLSFSUB2(HRESET,hreset,INT,STRING,A1,A2)
#define HROPEN(A1,A2,A3,A4,A5,A6) \
    CCALLSFSUB6(HROPEN,hropen,INT,STRING,STRING,STRING,INT,PINT,A1,A2,A3,A4,A5,A6)
#define HROUT(A1,A2,A3) \
    CCALLSFSUB3(HROUT,hrout,INT,INT,STRING,A1,A2,A3)
#define HREND(A1) \
    CCALLSFSUB1(HREND,hrend,STRING,A1)
#define HOPERA(A1,A2,A3,A4,A5,A6)  \
   CCALLSFSUB6(HOPERA,hopera,INT,STRING,INT,INT,FLOAT,FLOAT,A1,A2,A3,A4,A5,A6)

PROTOCCALLSFFUN1(FLOAT,HRNDM1,hrndm1,INT)
#define HRNDM1(A1)  CCALLSFFUN1(HRNDM1,hrndm1,INT,A1)
PROTOCCALLSFFUN1(LOGICAL,HEXIST,hexist,INT)
#define HEXIST(A2)  CCALLSFFUN1(HEXIST,hexist,INT,A2)
PROTOCCALLSFFUN2(FLOAT,HI,hi,INT,INT)
#define HI(A1,A2)   CCALLSFFUN2(HI,hi,INT,INT,A1,A2)
PROTOCCALLSFFUN2(FLOAT,HX,hx,INT,FLOAT)
#define HX(A1,A2)   CCALLSFFUN2(HX,hx,INT,FLOAT,A1,A2)
PROTOCCALLSFFUN3(FLOAT,HXY,hxy,INT,FLOAT,FLOAT)
#define HXY(A1,A2,A3) CCALLSFFUN3(HXY,hxy,INT,FLOAT,FLOAT,A1,A2,A3)

PROTOCCALLSFFUN1(FLOAT,HSUM,hsum,INT)
#define HSUM(A1)  CCALLSFFUN1(HSUM,hsum,INT,A1)
PROTOCCALLSFFUN1(FLOAT,HMAX,hmax,INT)
#define HMAX(A1)  CCALLSFFUN1(HMAX,hmax,INT,A1)
PROTOCCALLSFFUN1(FLOAT,HMIN,hmin,INT)
#define HMIN(A1)  CCALLSFFUN1(HMIN,hmin,INT,A1)
PROTOCCALLSFFUN2(FLOAT,HIE,hie,INT,INT)
#define HIE(A1,A2)   CCALLSFFUN2(HIE,hie,INT,INT,A1,A2)

/* ==== higz ================================================================ */

#define HPLINT(A1) \
    CCALLSFSUB1(HPLINT,hplint,INT,A1)
#define HPLOT(A1,A2,A3,A4) \
    CCALLSFSUB4(HPLOT,hplot,INT,STRING,STRING,INT,A1,A2,A3,A4)
#define HPLZON(A1,A2,A3,A4) \
    CCALLSFSUB4(HPLZON,hplzon,INT,INT,INT,STRING,A1,A2,A3,A4)
#define IGSA(A1) \
    CCALLSFSUB1(IGSA,igsa,INT,A1)
#define IOPWK(A1,A2,A3) \
    CCALLSFSUB3(IOPWK,iopwk,INT,INT,INT,A1,A2,A3)
#define IACWK(A1) \
    CCALLSFSUB1(IACWK,iacwk,INT,A1)
#define HPLTIT(A1) \
    CCALLSFSUB1(HPLTIT,hpltit,STRING,A1)
#define ITX(A1,A2,A3) \
    CCALLSFSUB3(ITX,itx,FLOAT,FLOAT,STRING,A1,A2,A3)
#define IUWK(A1,A2) \
    CCALLSFSUB2(IUWK,iuwk,INT,INT,A1,A2)
#define IGSSE(A1,A2) \
    CCALLSFSUB2(IGSSE,igsse,INT,INT,A1,A2)
#define IGINIT(A1) \
    CCALLSFSUB1(IGINIT,iginit,INT,A1)

PROTOCCALLSFFUN5(INT,IGPKFA,igpkfa,FLOAT,FLOAT,INT,FLOATV,FLOATV)
#define IGPKFA(A2,A3,A4,A5,A6)  CCALLSFFUN5(IGPKFA,igpkfa,FLOAT,FLOAT,INT,FLOATV,FLOATV,A2,A3,A4,A5,A6)

/* ==== paw ================================================================= */

#define PAWINT(PAWSIZE,HIGZSIZE,KUIPSIZE) \
    CCALLSFSUB3(PAWINT,pawint,INT,INT,INT,PAWSIZE,HIGZSIZE,KUIPSIZE)
#define PAEXIT(DUMMY) \
    CCALLSFSUB1(PAEXIT,paexit,INT,DUMMY)
#define PAW(A1,A2) \
    CCALLSFSUB2(PAW,paw,INT,INT,A1,A2)
#define PAWPP(A1,A2) \
    CCALLSFSUB2(PAWPP,pawpp,INT,INT,A1,A2)
#define PAWDEF() \
    CCALLSFSUB0(PAWDEF,pawdef)
#define RZPURG(A1) \
    CCALLSFSUB1(RZPURG,rzpurg,INT,A1)

/* ==== kuip ================================================================ */

#define KUWHAG(DUMMY) \
    CCALLSFSUB1(KUWHAG,kuwhag,INT,DUMMY)
#define KUWHAT() \
    CCALLSFSUB0(KUWHAT,kuwhat)
#define KUWHAM(A1) \
    CCALLSFSUB1(KUWHAM,kuwham,PSTRING,A1)
#define KUPATL(CHPATL,NPAR) \
    CCALLSFSUB2(KUPATL,kupatl,PSTRING,PINT,CHPATL,NPAR)
#define KUINIT(A1) \
    CCALLSFSUB1(KUINIT,kuinit,INT,A1)
#define KUGETC(A1,A2) \
    CCALLSFSUB2(KUGETC,kugetc,PSTRING,PINT,A1,A2)
#define KUGETF(A1,A2) \
    CCALLSFSUB2(KUGETF,kugetf,PSTRING,PINT,A1,A2)
#define KUGETE(A1,A2) \
    CCALLSFSUB2(KUGETE,kugete,PSTRING,PINT,A1,A2)
#define KUGETH(A1,A2) \
    CCALLSFSUB2(KUGETH,kugeth,PLONG,PINT,A1,A2)
#define KUGETI(A1) \
    CCALLSFSUB1(KUGETI,kugeti,PINT,A1)
#define KUGETR(A1) \
    CCALLSFSUB1(KUGETR,kugetr,PFLOAT,A1)
#define KUGETS(A1,A2) \
    CCALLSFSUB2(KUGETS,kugets,PSTRING,PINT,A1,A2)
#define KUEXEC(A1) \
    CCALLSFSUB1(KUEXEC,kuexec,STRING,A1)
#define KUEXIT(A1) \
    CCALLSFSUB1(KUEXIT,kuexit,PVOID,A1)
#define KUQUIT(A1) \
    CCALLSFSUB1(KUQUIT,kuquit,PVOID,A1)

/* ==== genlib, kernlib, ... ================================================ */

#define IE3FOS(VSINGL,VIEEES,NV,JCODE) \
    CCALLSFSUB4(IE3FOS,ie3fos,PFLOAT,PFLOAT,INT,PINT,VSINGL,VIEEES,NV,JCODE)
#define IE3TOS(VSINGL,VIEEES,NV,JCODE) \
    CCALLSFSUB4(IE3TOS,ie3tos,PFLOAT,PFLOAT,INT,PINT,VSINGL,VIEEES,NV,JCODE)

/* ==== diverse ============ ================================================ */

#define NORRAN(A1) \
    CCALLSFSUB1(NORRAN,norran,PFLOAT,A1)

#endif
